apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "servox.fullname" . }}
  labels:
    {{- include "servox.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/status", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "pods/logs", "pods/status"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
